services:
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    networks:
      - otus
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./app/src/public:/application/public
    ports:
      - "80:80"
    networks:
      - otus
  redis:
    image: redis
    networks:
      - otus
  memcached:
    image: memcached:latest
    networks:
      - otus
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
    networks:
      - otus

networks:
  otus:
    driver: bridge