services:
  php-fpm1:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    networks:
      - otus
    volumes:
      - ./app:/application
    tty: true
    environment:
      - REDIS_HOST=redis
  php-fpm2:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    networks:
      - otus
    volumes:
      - ./app:/application
    tty: true
    environment:
      - REDIS_HOST=redis
  nginx-balancer:
    build:
      context: docker/nginx-balancer
      dockerfile: Dockerfile
    volumes:
      - ./app/public:/application/public
    ports:
      - "80:80"
    networks:
      - otus
  web1:
    build:
      context: docker/nginx-web
      dockerfile: Dockerfile
    networks:
      - otus
  web2:
    build:
      context: docker/nginx-web
      dockerfile: Dockerfile
    networks:
      - otus
  redis:
    image: redis
    networks:
      - otus
  memcached:
    image: memcached:latest
    networks:
      - otus
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: root
    networks:
      - otus

networks:
  otus:
    driver: bridge